# This workflow will run the tests on CI

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup node 
      uses: actions/setup-node@v3
      with:
        node-version: 16.0.0
        cache: 'npm'

    - name: Install dependencies    
      run: npm install

    - name: Run tests  
      run: npm test

    - name: Upload test results
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: testReport
        path: test-reports 
